import {
	boolean,
	integer,
	pgEnum,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uuid,
} from "drizzle-orm/pg-core";

// Enums
export const languageEnum = pgEnum("language", ["en", "fr", "mixed"]);
export const importSourceEnum = pgEnum("import_source", ["app", "whatsapp"]);

// Users table - matches Supabase Auth ID
export const users = pgTable("users", {
	id: uuid("id").primaryKey(), // Matches Supabase Auth ID
	email: text("email").notNull().unique(),
	displayName: text("display_name"),
	createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Recordings table
export const recordings = pgTable("recordings", {
	id: uuid("id").primaryKey().defaultRandom(),
	userId: uuid("user_id")
		.notNull()
		.references(() => users.id),
	audioUrl: text("audio_url").notNull(),
	durationSeconds: integer("duration_seconds"),
	fileSizeBytes: integer("file_size_bytes"),
	transcript: text("transcript"),
	language: languageEnum("language"),
	recordedAt: timestamp("recorded_at").notNull(),
	importSource: importSourceEnum("import_source").default("app").notNull(),
	originalFilename: text("original_filename"),
	notes: text("notes"), // Optional text context from WhatsApp import
	createdAt: timestamp("created_at").defaultNow().notNull(),
	updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Keywords table
export const keywords = pgTable("keywords", {
	id: uuid("id").primaryKey().defaultRandom(),
	name: text("name").notNull().unique(),
	createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Junction table for recordings and keywords
export const recordingKeywords = pgTable(
	"recording_keywords",
	{
		recordingId: uuid("recording_id")
			.notNull()
			.references(() => recordings.id, { onDelete: "cascade" }),
		keywordId: uuid("keyword_id")
			.notNull()
			.references(() => keywords.id, { onDelete: "cascade" }),
		isAutoGenerated: boolean("is_auto_generated").default(true).notNull(),
	},
	(t) => [primaryKey({ columns: [t.recordingId, t.keywordId] })],
);

// Type exports
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Recording = typeof recordings.$inferSelect;
export type NewRecording = typeof recordings.$inferInsert;

export type Keyword = typeof keywords.$inferSelect;
export type NewKeyword = typeof keywords.$inferInsert;

export type RecordingKeyword = typeof recordingKeywords.$inferSelect;
export type NewRecordingKeyword = typeof recordingKeywords.$inferInsert;
